### ISSUE TITLE
Overflow on smaller screen resolutions

### ISSUE THREAD

**Issue by chloetruax** [Errorcod3/Week1Day5_Classwork#1]
When on smaller screen resolutions, the declared main container height causes content overflow on the y-axis.

Removing line 63 in `master.css`  should fix it:

``` css
.mainContainer{
  width: 100%;
  height: calc(100vh - 65px); /* This line causes the overflow issues */
  background-color: #CF9893;
}
```
