### ISSUE TITLE
Non DRY CSS

### ISSUE THREAD

**Issue by chloetruax** [Errorcod3/Week1Day5_Classwork#2]
You're utilizing `float: left;` in several places as well as `text-align: center;` try to break those down into helper classes:
``` CSS
.textCenter{
  text-align: center;
}
```

Also, the use of float might not be needed if you wrapped everything in a flex box and only utilized flex throughout the page.
