### ISSUE TITLE
Unclear class naming

### ISSUE THREAD

**Issue by chloetruax** [Errorcod3/Week1Day5_Classwork#4]
The `margin` class and the `height` class are clear in the CSS what they do but unclear in the HTML
`margin` also has a border attribute that should be moved into its own class.

``` CSS
.margin-5{
  margin: 5px;
}
.border-2{
  border: 2px solid  #2E294E;
}

.fullHeight{
height: 100%;
}
```

Also remember height 100% only works in specific cases as the % relative size only works in some cases.
